### PR TITLE
Removed unused dependency that prevented installation in laravel 5.7

### PR DESCRIPTION
**Pull request by gpressutto5**

### CODE REVIEW

**Comment by highsolutions** [comment]
Thank you for pointing that problem. But we cannot remove this package due to be able to perform unit tests. Instead we prepared 3.0 version which supports all versions of Laravel. 
Please check: [https://github.com/highsolutions/eloquent-sequence/releases/tag/3.0.0](https://github.com/highsolutions/eloquent-sequence/releases/tag/3.0.0)

**Comment by highsolutions** [comment]
@gpressutto5 you are right. We've released the 2.6.3 version with this change for easier update of package.

[https://github.com/highsolutions/eloquent-sequence/releases/tag/2.6.3](https://github.com/highsolutions/eloquent-sequence/releases/tag/2.6.3)

**Comment by gpressutto5** [comment]
I'm sorry, but I will need to continue using my fork. You shouldn't have removed `illuminate/support` since it is a dependency. If your package can't run in a production environment without dev dependencies it is broken.
It's easy: if your package use it in production, it's a dependency, otherwise it's a dev dependency.

**Comment by highsolutions** [comment]
You're right (again :P).

Another release fixing that problem:
[https://github.com/highsolutions/eloquent-sequence/releases/tag/2.6.4](https://github.com/highsolutions/eloquent-sequence/releases/tag/2.6.4)

**Pull request closed without merging**
